# Generated by Django 4.1.7 on 2023-04-02 16:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post_created', models.DateTimeField(auto_now_add=True)),
                ('post_updated', models.DateTimeField(auto_now=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
