# Generated by Django 4.1.7 on 2023-04-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_blogpost_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_para',
            field=models.CharField(default='mani', max_length=255),
        ),
    ]
